name: shopping_helper_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  camera: ^0.10.5+4
  flutter:
    sdk: flutter
  flutter_tts: ^3.8.1  
  speech_to_text: ^6.3.0
  video_player: ^2.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
