name: shopping_helper_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  camera: ^0.10.5+4
  flutter:
    sdk: flutter
  flutter_tts: ^3.8.1  
  speech_to_text: ^6.3.0
  http: ^1.1.0
  image: ^4.1.3
  # tflite: ^1.1.2
  # tflite_v2: ^1.0.0
  logger: ^2.0.2+1
  permission_handler: ^11.0.1
  # video_player: ^2.7.1
  # flutter_image_compress: ^2.0.4
  # image: ^4.0.17
  # tflite: ^1.1.2
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
